### ISSUE TITLE
Remove workaround for "pq: could not serialize access due to read/write dependencies among transactions"

### ISSUE THREAD

**Issue by invidian** [tinkerbell/terraform-provider-tinkerbell#22]
https://github.com/tinkerbell/tink/issues/338 has been resolved, so we should be able to mostly remove it (as deleting workflows seems to be still affected).

**Comment by cpanato** [comment]
@invidian you mean remove the error check for that? or there is more code? asking that because I did not see any `TODO` in the code related to this

found this only: https://github.com/tinkerbell/terraform-provider-tinkerbell/blob/5bbe5431baefedc9b7a5723c34ef0586b4a78752/tinkerbell/resource_hardware.go#L107

**Comment by invidian** [comment]
>@invidian you mean remove the error check for that? or there is more code? asking that because I did not see any TODO in the code related to this

I think we can remove the calls to `retryOnTransientError` from everywhere except the workflow removal code, as it still requires it.

But before doing that, we need to make sure that sandbox version we use includes https://github.com/tinkerbell/tink/pull/346.

Perhaps we could also wait for https://github.com/tinkerbell/tink/pull/395.

**Comment by cpanato** [comment]
@invidian both are merged, do you think we can move forward?

**Comment by invidian** [comment]
True, thanks for the heads up. Also sandbox repository got updated by now, for which I created the PR already (https://github.com/tinkerbell/terraform-provider-tinkerbell/pull/23).

However, I hit this issue: https://github.com/tinkerbell/tink/issues/413 and I'm still wondering if we should update to newer version.

**Comment by invidian** [comment]
Actually, https://github.com/tinkerbell/tink/issues/338 has been re-opened, as it still occurs when resources are removed.

**Comment by tstromberg** [comment]
@invidian - can you point to the location of the workaround in the code base?

**Comment by cpanato** [comment]
still willing to help :)

**Comment by invidian** [comment]
https://github.com/tinkerbell/terraform-provider-tinkerbell/blob/bab1eaa135a030c8da0c461aa5beb84b00f24567/tinkerbell/resource_hardware.go#L107-L121 is still there.

**Comment by jacobweinstock** [comment]
The Tinkerbell stack has moved to a [Kubernetes resource model](https://github.com/tinkerbell/proposals/blob/main/proposals/0026/README.md) and [deprecated the postgres backend](https://github.com/tinkerbell/proposals/blob/main/proposals/0029/README.md). This repo is scheduled to be archived.
