### ISSUE TITLE
Hardware should accept a TF schema that maps to Hardware data fields

### ISSUE THREAD

**Issue by displague** [tinkerbell/terraform-provider-tinkerbell#5]
The Hardware schema is currently a `data` string represented a JSON structure which represents the Tinkerbell hardware data: https://tinkerbell.org/docs/hardware-data/ (https://github.com/tinkerbell/tink/blob/master/protos/hardware/hardware.pb.go#L154-L158).

`data` is the response envelopment and manipulating this value in Terraform does not provide a good UX.  Users should be able to easily interact with the components of this structure in Terraform native types.

The Hardware type should be implemented in Terraform schema.

**Comment by jacobweinstock** [comment]
The Tinkerbell stack has moved to a [Kubernetes resource model](https://github.com/tinkerbell/proposals/blob/main/proposals/0026/README.md) and [deprecated the postgres backend](https://github.com/tinkerbell/proposals/blob/main/proposals/0029/README.md). This repo is scheduled to be archived.
