### ISSUE TITLE
Template type should be implemented in Terraform schema

### ISSUE THREAD

**Issue by displague** [tinkerbell/terraform-provider-tinkerbell#6]
The [Template schema is currently a `content` string](https://github.com/kinvolk/terraform-provider-tinkerbell/blob/master/tinkerbell/resource_template.go#L28-L32) represented a YAML structure which represents the Tinkerbell workflow template data: https://tinkerbell.org/docs/hardware-data/ (https://github.com/tinkerbell/tink/blob/master/pkg/types.go).

`content` is an abstraction around the native GRPC data type and manipulating this value as a string in Terraform does not provide a good UX.  Users should be able to easily interact with the components of this structure in Terraform native types.

The Template type should be implemented in Terraform schema.

**Comment by jacobweinstock** [comment]
The Tinkerbell stack has moved to a [Kubernetes resource model](https://github.com/tinkerbell/proposals/blob/main/proposals/0026/README.md) and [deprecated the postgres backend](https://github.com/tinkerbell/proposals/blob/main/proposals/0029/README.md). This repo is scheduled to be archived.
