### ISSUE TITLE
Workflow `hardwares` type should be a native Terraform schema, not string

### ISSUE THREAD

**Issue by displague** [tinkerbell/terraform-provider-tinkerbell#8]
The [Workflow schema is currently including a `hardwares` string](https://github.com/kinvolk/terraform-provider-tinkerbell/blob/master/tinkerbell/resource_workflow.go#L21-L27) represented a JSON structure which represents the Tinkerbell workflow `hardware` data: https://tinkerbell.org/docs/workflows/ (https://github.com/tinkerbell/tink/blob/master/protos/workflow/workflow.pb.go#L226), this is generally a list of devices.

Unlike #5 and #6, `hardwares` is faithfully representing the native GRPC data type (or I just can't find a more detailed type).  None the less, manipulating this value as a string in Terraform does not provide a good UX.  Users should be able to easily interact with the components of this structure in Terraform native types.  And yet, Terraform should provide a 1:1 interface with the API whenever possible.

Perhaps the Tinkerbell API should introduce more structure around the Workflow Hardware type?

I would like to see the `hardware` type implemented as Terraform schema, a slice of maps that contain devices and other properties, but this may require Tinkerbell API changes or clarity first.

**Comment by jacobweinstock** [comment]
The Tinkerbell stack has moved to a [Kubernetes resource model](https://github.com/tinkerbell/proposals/blob/main/proposals/0026/README.md) and [deprecated the postgres backend](https://github.com/tinkerbell/proposals/blob/main/proposals/0029/README.md). This repo is scheduled to be archived.
